### ISSUE TITLE
Videos folder structure

### ISSUE THREAD

**Issue by AVCarreiro** [hehefan/video-classification#2]
Hi, thank you for sharing your work! :) 

I was trying to run the code, but stumbled with some differences in the folder structure of UCF101. When I unrar, I get a folder per class, and within it, a bunch of class-related videos. But in your script (and then in the actual code for feature extraction), it's assuming you have just a folder with all videos:

`for video in 'ls ucf101-videos'; do
  mkdir -p ucf101-frames/$video
  ffmpeg -i ucf101-videos/$video -vf fps=1 ucf101-frames/$video/%04d.jpg`

I'd appreciate if you could explain what is expected here, and if any transformation from the UCF101.rar is required. Thanks!

**Comment by hehefan** [comment]
Did you download the dataset from the page http://crcv.ucf.edu/data/UCF101.php or the url http://crcv.ucf.edu/data/UCF101/UCF101.rar?

**Comment by AVCarreiro** [comment]
Hi,

I downloaded from the link in the shell script, the second one (directly the .rar). I managed to make it work but had to change some paths.

I'm on Windows, and it occurred to me that it might be a path-related issue (path separator being transparently read by ffmpeg in linux, for example)

**Comment by hehefan** [comment]
First, you need to make sure your Windows is capable of running shells. Second, you need to replace '/' with '\' in each path-related commands or codes.
